language: node_js
node_js: 
  - "stable"
cache:
  - bundler
  directories:
    - "node_modules"
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: dungeon-crawler-a
  on:
    repo: RTatineni/dungeon-crawler